name: Deploy Site on push
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v2.3.2
    - uses: actions/setup-node@master
    - name: Installing project dependencies
      run: npm install
    - name: Building the project
      run: npm run build
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        local-dir: ./build/
        server-dir: ./enc-at-rest/
        server: ${{ secrets.SLABS_FTP_SERVER}}
        username: ${{ secrets.SLABS_FTP_USER}}
        password: ${{ secrets.SLABS_FTP_PASSWORD}}
